<a href="https://colab.research.google.com/github/kamaleshcoder/Machine-Learning-basic-Libraries/blob/main/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy - Numperical Python



advantages
1. allows sevaeral numerical operations
2. faster operations

In [ ]:
import numpy as np


list vs numpy time taken

In [ ]:
from time import process_time

time taken by list

In [ ]:
python_list = [i for i in range(1000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0001441599999996157


In [ ]:
np_array = np.array([i for i in range(1000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)



0.0005940600000000629


numpy array

In [ ]:
list1 = [1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [ ]:
np_array = np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

In [ ]:
# 1d array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

initial placeholders

In [ ]:
#zero array
x = np.zeros((4,5),dtype=int)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# 1 array
x = np.ones((4,5),dtype=int)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
# particular values
x = np.full((4,4),6)
print(x)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [ ]:
#identity matrix
a = np.eye(10)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#random values

b = np.random.randint(10,100,(3,4))
print(b)

[[66 89 64 11]
 [13 65 71 59]
 [46 61 19 60]]


list to numpy

In [ ]:
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)

print(np_array)

[10 20 30 40 50]
